### ISSUE TITLE
Is there any way to check if a specific peerId already exists?

### ISSUE THREAD

**Issue by luongnv89** [peers/peerjs#180]
Hi,
I got error message "PeerJS:  ERROR Aborting. Error: ID `idtest` is taken" when I try to create two peers which are same id.
Is there any way to check if a specific peerId already exists?
Thanks,

**Comment by WofWca** [comment]
> you can catch that error (I believe the type is unavailable-id--http://peerjs.com/docs/#peeron-error) and try a new ID

Here's the [updated link](https://github.com/michelle/jquery.peer/blob/b5042338d99d86a5e898a3e98b10818c0943e90b/lib/jquery.peer.js#L173C5-L176).

This is problematic, because apparently nowadays the peerjs-server allows you to take an ID even if it's occupied, given that you try to take it from the same machine (even a different browser).
