### ISSUE TITLE
unavailable-id after internet connection lost

### ISSUE THREAD

**Issue by alioguzhan** [peers/peerjs#224]
Hey,
this is how i reproduce this error:

if i close and re-open internet connection, it throws this error.

```
PeerJS:  WARNING You received a malformed message from undefined of type HTTP-ERROR peer.js:1117
PeerJS:  Socket open peer.js:1117
PeerJS:  ERROR Aborting. Error: ID `1` is taken peer.js:1117
```

and i dont use random ids generated from peerserver. a client's peer id is always same and unique (i am getting it from user's primary key value from database)

It is ok while i am switchinh between my web sites pages. (i put peer initialization code in my base.js which loads in every page) ,

swtiching between pages is a kind of disconnection from server right? but why does this happen only when internet connection lost?

i handle this error under `peer.on('error')`, although i write peer.destroy() here, i doesn't work.

**Comment by ncri** [comment]
Any progress/workarounds here? Just ran into the same issue...

**Comment by trakers33** [comment]
Same for me

**Comment by arjehouw01** [comment]
I ran into the same problem. Is peer.reconnect an option?

**Comment by trakers33** [comment]
Just destroy and connect. Reconnect gonna fail too

**Comment by shashvattrip** [comment]
Still facing this issue. @peers please solve this issue.

**Comment by shashvattrip** [comment]
@michelle : I have a temporary solution. When the peer server emits an error saying that peer id is taken, can we check if there are any active connections on the same id. If no, then the peer server can flush destroy that peer id from the server. Would this work?

**Comment by ncri** [comment]
Any updates here? peerjs doesn't seem to be very maintained. I might try to modify the peer server and try out your idea @shashvattrip.

**Comment by shashvattrip** [comment]
Hey @ncri , yes please do. I too will try it out soon once i get a little time from my current project.

**Comment by ncri** [comment]
Okay, well, also a bit short on time, but hope to look into it soon. So far I got a working solution, although not a very satisfying one: after a few retries the id becomes available again...

**Comment by shashvattrip** [comment]
Yes, same here. I have tried changing the peer id on id not available. But I don't want to hack it, there needs to be a straight forwards working mechanism to handle this scenario

**Comment by ncri** [comment]
I was able to avoid the error by passing in the same token when recreating the peer object after the connection is back. Not sure if this is ideal, but it works well so far.

**Comment by interfaith** [comment]
If peerjs-server can be modified to remove that user, that will do. Is there a working fix now ?

**Comment by bialabs** [comment]
same problem here.  tried with peer.destroy() but nothing. Anyone can help me?

**Comment by domschiener** [comment]
Anyone found a good solution yet? I'm using hardcoded ID's to make it easy for people to connect to each other and store local data (about the other peer), so changing ID's is not the nicest solution for me.

**Comment by forrana** [comment]
https://github.com/peers/peerjs/blob/master/dist/peer.js#L733
Can someone explain the meaning of this string?

I made an investigation in server code and found that issue in that string, probably.
https://github.com/peers/peerjs-server/blob/master/lib/server.js#L255

So how it works now - client every time when reconnect, generate a new token, server check it and generate an error message in response.
How I solve it:

`
const token = util.randomToken();
...
  options = util.extend({
    debug: 1, // 1: Errors, 2: Warnings, 3: All logs
    host: util.CLOUD_HOST,
    port: util.CLOUD_PORT,
    key: 'peerjs',
    path: '/',
    token: token,
    config: util.defaultConfig
  }, options);
`

What possibly wrong could be with my solution?
Because I really don't understand why we can't keep one token for a page.

**Comment by rahilka** [comment]
Any updates on this issue? peer.destroy() is not helping...

**Comment by LucaColombi** [comment]
Same problem after 4 years, I suppose there is a maintainance problem :|

Is there a id timeout or a way to stimulate the real taken status of an ID?

**Comment by kidandcat** [comment]
Hi, we are maintaining it again, but I cannot go through all old issues checking if they have been fixed or not, browsers have changed a lot.

Let me give it a look to see if I can find a solution. Of course any contribution is welcome.

**Comment by kidandcat** [comment]
As mentioned before, the close event don't work for lost connections very well. My idea is to give a unique token (password) when you connect using an ID, and if another peer connects using that ID and that token, then I will suppose it is you, and will accept your connection.

What do you think about this approach?

**Comment by LucaColombi** [comment]
Hello, 

technically, it would work, but I am concerned about security vulnerabilities, in this way, I can in any moment impersonate another ID and get messages that were directed to him.

If there are no other ways, your solution is better than nothing, so static token ids can works with peerJS (otherwise we would need to excange dinamic ids.. almost like another signaling server)

I would have some idea to improve security, I don't know the under code so I am telling things that could be easy or not to do, you evaluate the feasibility:

Is there possibile to check a lost connection with a timeout and autodisconnect the lost connections?
Otherwise on demand (this would be lesser resource consuming), when the same id reconnect, is it possible to check if the previous connection is alive (like a ping)? if the previous answer in X seconds the new connection is refused, otherwise, the previous is closed and the new wins, is it possible?

Thank you for your time

**Comment by kidandcat** [comment]
Well, you will not be able to impersonate because you need the initial Token (password) PeerServer sent to you the first time you connected.

**Comment by LucaColombi** [comment]
o ok, I didnt know the protocol, so seem perfect

**Comment by LucaColombi** [comment]
Hello,

it seems to me that the token is already shoult be used to accept the user connection in the server, is it possible? Can you tell me if I am wrong?

in this case the problem would be that the token changes, it could by simply reloading the page if not put in a cookie or similar, as a fix, could the token be forced in the client side?

```
app._configureWS = function(socket, key, id, token) {
  var self = this;
  var client = this._clients[key][id];

  if (token === client.token) {
    // res 'close' event will delete client.res for us
    client.socket = socket;
    // Client already exists
    if (client.res) {
      client.res.end();
    }
  } else {
    // ID-taken, invalid token
    socket.send(
      JSON.stringify({ type: "ID-TAKEN", payload: { msg: "ID is taken" } })
    );
    socket.close();
    return;
  }
```

**Comment by afrokick** [comment]
We added heartbeat message from client to server. So, i think we can check it and close connection if it missed

**Comment by afrokick** [comment]
fixed in 1.0.4+

**Comment by Fayozjon** [comment]
Same error NOT FIXED yet

**Comment by jose920405** [comment]
Still happening and is sporadic

**Comment by naveedaziz** [comment]
Its killing,,,,, what to do for the error

**Comment by naveedaziz** [comment]
Does PeerJS is recommended for some major projects. As these kind of errors killing the project.
