### ISSUE TITLE
google chrome version 47

### ISSUE THREAD

**Issue by jigarrdesai** [peers/peerjs#324]
peerjs fail to access microphone and webcam

**Comment by luongnv89** [comment]
You may see this warning:
"getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details"

**Comment by Maykonn** [comment]
I using SSL. The request are made directly to port 443 and proxied to 9000, but WS or WSS returning the following error:

**ERR_DISALLOWED_URL_SCHEME**

More details here: [](https://github.com/peers/peerjs/issues/327)

**Comment by blq** [comment]
To add some more information; As said above, running on https for webcam access is now needed. _But_ this means that PeerJS' stops working, since the signalling server (0.peerjs.com) uses plain http, and is thus stopped by traditional mixed-content blocking!
I really hope PeerJS can add https support soon, this is now a showstopper almost

**Comment by Maykonn** [comment]
I'm don't using the PeerJS cloud server. I'm trying to run from AWS S3 the js files and requesting to an EC2 instance with Node.js. And apache proxy.
