### ISSUE TITLE
How to disconnect call before user accept

### ISSUE THREAD

**Issue by akilah007** [peers/peerjs#328]
Call not disconnecting from user end after disconnect call. It's shows ringing. Can answer the call also.
How to disconnect call before user accept.

**Comment by dlinx** [comment]
You can close media connection using `call.close();`. [Here](http://peerjs.com/docs/#mediaconnection-close) is reference.

**Comment by BernardoMG** [comment]
I have the same question. `call.close()` doesn't work if you don't do `call.anwser()` first...

**Comment by andreassh** [comment]
I'm experiencing the same problem as @BernardoMG . Works fine if call.close() is called after call.answer(), but no if you call call.close() before call is answered.

**Comment by capripio** [comment]
@akilah007 @dlinx @BernardoMG @andreassh 
Anyone of you guys found any work around here?

**Comment by LocusSage** [comment]
Well. the only workaround I've found was to create a data channel between the peers and send an finish object that finishes the call on the other end

**Comment by afrokick** [comment]
we can add 'decline' method, which send back decline message to callee via signaling.

**Comment by kidandcat** [comment]
Well, for the disconnecting problem, we could set some kind of heartbeat using DataChannel (or with PeerServer between)

**Comment by asd0999** [comment]
well, this is not the best solution but i use web sockets to relay different states and synchronize between caller and receiver. so if caller hangs up before the receiver picks up, i revert to the "before call was initiated" state on the callers side and use the web socket to relay that the call was disconnected to the receiver side so the receiver can also go back to the "before call was initiated" state. but note: the peer connection is not disconnected because call.close() doesnt work without the call being answered. so this is essentially a work around to make the UI feel like the call ended but actually the "call" is just hanging in limbo

**Comment by bilo1967** [comment]
> 
> 
> You can close media connection using `call.close();`. [Here](http://peerjs.com/docs/#mediaconnection-close) is reference.

Broken link

**Comment by bilo1967** [comment]
Any chance this decline/reject new feature will be implemented soon?

**Comment by MatthewPringle** [comment]
Really could do with a decline method

**Comment by ergilaze** [comment]
Same. Decline method would be really appreciated.

**Comment by marcjulianfleck** [comment]
Still waiting for this feature. :/
