### ISSUE TITLE
volume controll and screen capture

### ISSUE THREAD

**Issue by nileshlets** [peers/peerjs#335]
How can we set sound mute and volume up down ?
And is there an example for screen capture and call record?

**Comment by bradisbell** [comment]
> How can we set sound mute and volume up down ?

Best to leave this up to the user.  They're already used to adjusting volume with their own volume controls, and doing it in-application can lead to additional confusion when maximum volume isn't good enough because volume is turned down elsewhere.  If you really needed to do this for some reason (like mute), you can use a GainNode with the Web Audio API.

> And is there an example for screen capture

When you  use getUserMedia(), you can specify window or screen capture in your video constraints.  Note that there is limited browser support.  In Firefox, you must whitelist your application in advanced settings (or provide a browser extension that does this).

> and call record?

For this, you need the MediaRecorder.  https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder
