### ISSUE TITLE
Detect ended call

### ISSUE THREAD

**Issue by renebrain** [peers/peerjs#345]
Hi,

we have implemented the peer.js library together with the peer.js broker server. I just have one problem. How do i know on client side, when the stream is over? For example the other user closes the Window or something like that. The close event is never fired at this time, so i never know if the stream ended or not, i just see that the image freezes because the stream is not send anymore. Is there a way to detect that? As far as i understood Firefox is not emitting this event. But neither did Chrome or Opera for me.

Any help? How do you detect the end of the call?

**Comment by SengitU** [comment]
Hello,

Does the term end close peer connection before terminating call? Because If a party just closes the call without informing other end, AFAIK webrtc engine will not fire any event. 

If terminating end destroys the peer connection, then peer.onClose event should be fired and handled. 
In order to handle unexpected crashes, you will probably need to implement a audit mechanism.

Regards,
Ugurcan
