### ISSUE TITLE
PeerJS clients in two Chrome tabs cannot receive data from connection

### ISSUE THREAD

**Issue by muoitranduc** [peers/peerjs#375]
I face this problem today in Chrome, but not in Firefox.
I open two clients in two tabs. Entering the other peer's id, one peer becomes "connection establisher" or simply "sender" and the other peer is "receiver".
Then the "receiver" **cannot** send the message to the "sender" while sender still can send the message to the receiver.
I also try your demo page http://cdn.peerjs.com/demo/chat.html but it seems PeerJS has some problems with the latest Chrome update.
Kindly check to see if it's a problem or I just did something wrong.
Thanks,

**Comment by jeffslofish** [comment]
I am able to consistently duplicate this bug with the following steps:

1. Open a new Chrome window.
2. Enter `http://cdn.peerjs.com/demo/chat.html` in the navigation bar.
3. Click the "+" to open a new tab.
4. Enter `http://cdn.peerjs.com/demo/chat.html` in the navigation bar of the second tab.
5. Copy the PeerJS ID from the second tab and paste it into the "Connect to a peer" field on the first tab.
6. In the first tab, send a message.
7. Go to the second tab (the first message should be there).
8. Send a message from the second tab.
9. Go to the first tab (the second message is not there)!

Note 1: If on step 3, you choose "duplicate tab" instead of creating a new tab with the "+", then it seems to work correctly, and the second message does appear on the first tab.

Note 2: I was testing this with Chrome 58.0.3029.81 (64-bit) on MacOS Sierra 10.12.4

**Comment by bolahanna44** [comment]
why duplicating tab make it work and opening a new tab doesn't make it work ??

**Comment by mayoljonathan** [comment]
I got it working.
Check out my fork.
https://github.com/mayoljonathan/peerjs/blob/master/examples/chat.html#L65

**Comment by bolahanna44** [comment]
it is not a good option wot work with this library since it is not maintained i used webrtc with firebase as a signaling server and i think this is the best option

**Comment by afrokick** [comment]
https://peerjs.com/docs.html#dataconnection-on-open on this event dataConnection.open should be 'true'
