### ISSUE TITLE
Which is faster PeerJS or Socket.io p2p

### ISSUE THREAD

**Issue by Kitanga** [peers/peerjs#378]
Loving what you have here. I really want to do something big with this. But, I'll keep those details to myself for now ;D

Now my question, is this faster than socket.io p2p and, also, is there a websocket fallback already implemented into PeerJS?

**Comment by WiseNN** [comment]
+1 for this question

**Comment by Kitanga** [comment]
@WiseNN sadly this repo is abandoned. Try out these other options though:

- [Simple Peer](https://github.com/feross/simple-peer)
- [Simple WebRTC](https://github.com/andyet/SimpleWebRTC)

**Comment by kidandcat** [comment]
There isn't any fallback built in PeerJS, as it is an abstraction layer for WebRTC only.

**Comment by Kitanga** [comment]
@kidandcat does you replying mean that this library is live again?

**Comment by kidandcat** [comment]
Yes, I became the new maintainer last October more or less. Library has been stabiliced since then. Most of the PRs have been merged and critical bugs have been fixed. I've launch servers again (PeerServer and website) and a few features have been pushed like default SSL.

I don't have much time, but I'm commited to keep this project alive and growing with everyone's help.
