### ISSUE TITLE
Not allowed to load local resource: blob:null/[random-hashes]

### ISSUE THREAD

**Issue by rt-2** [peers/peerjs#399]
I'm trying the example demo, running from localhost and using my own server on port 9000, at first didn't worked, then was able to get id from server again but then this:
![image](https://user-images.githubusercontent.com/3452428/30699987-417323b4-9eb4-11e7-8a49-a62d5d0f2b0a.png)
Also I dont know is the last request was supposed to be empty like this:
![image](https://user-images.githubusercontent.com/3452428/30700193-e5a0696a-9eb4-11e7-9742-019b3c91e53e.png)

Thank you,
rt-2

**Comment by abardik** [comment]
Try to load the page via http://localhost, not file://

**Comment by rt-2** [comment]
Also the API must be loaded in HTTPS.

**Comment by abardik** [comment]
Not for localhost, http is ok for development (localhost only).

**Comment by rt-2** [comment]
Not even, You would have to start Chrome with `chrome --allow-file-access-from-files` if you wanted to try localhost.

**Comment by cnlohr** [comment]
Since this shows up on google for this issue, while it's not directly against this repo - for anyone else who landed here, the mechanism for blob URL-ing can be modified to allow usage on file:// in chrome. Outlined https://stackoverflow.com/a/67125196/2926815 and https://stackoverflow.com/a/72180421/2926815, you can, instead of 

`const dataURI = URL.createObjectURL( new Blob([_data_blob_], { type: 'text/javascript', } ) );`

```js
    let blob = new Blob([bypass], {type: 'application/javascript'});
    let reader = new FileReader();
    await reader.readAsDataURL(blob);
    let dataURI = await new Promise((res) => {
        reader.onloadend = function () {
            res(reader.result);
        }
    });
    ```
