### ISSUE TITLE
Delay in time at event "disconnected".

### ISSUE THREAD

**Issue by opxwebdev** [peers/peerjs#464]
Hi.
I have the following problem. When a connection is closed by one of the clients, the second client receives a "disconnected" event about one minute after the connection is closed. Although the message "PeerJS: iceConnectionState is disconnected, closing connections to ..." is displayed in the console almost instantly.
Is it possible to add an event handler for the "iceconnectionstatechange" event? Or maybe there is another way to handle the "disconnected" event more quickly?

**Comment by kidandcat** [comment]
Due to the possibility of a quickly reconnect to be transparent to the client, the disconnect event is sent when the timeout ends after the last heartbeat received. You can use your custom disconnect event and launch it just before disconnecting, or you can lower the timeout between heartbeats, but if you do that, you may have issues in high latency connections.

I need to check how to change the timeout.

**Comment by opxwebdev** [comment]
Thanks for the quick answer. If it is not too hard for you, can you add a small example of how to add a custom event and the main thing is how to start it before disconnecting? I understand that reducing the delay time causes problems, but I would like, for example, to show the connection status to the user, so adding a user event will be enough for me. Thanks.

**Comment by opxwebdev** [comment]
Thanks for the answer. Made through the event "onbeforeunload". Probably not the best solution, but I just send a message through DataConnection, that the client on the other side closed the window. I would hope that in the future browser manufacturers will not make more stringent rules on the use of the "onbeforeunload" event, because in practice sometimes there are problems with it.
