### ISSUE TITLE
Error 429: Rate Limited from Zeit.co

### ISSUE THREAD

**Issue by pReya** [peers/peerjs#471]
I've been getting a lot of "429: Rate Limited" errors from Zeit.co, both when accessing the website and when creating new Peer() calls in the library. Is this a per-user limit? How high is the limit? I've only been doing manual testing over a couple of days. Probably a couple of dozen requests per day.

**Comment by kidandcat** [comment]
It's a global limit, and it is applied to the hosting provider where the public cloud server is hosted. I should look for other provider, or make it easy to deploy your own servers.

**Comment by pReya** [comment]
Thanks for clearing that up. So I guess currently you're using the free Zeit plan with 1000 req/day, correct? Wouldn't it be possible to host the public cloud server in the free tier of Google Cloud Platform via Google App Engine? If I'm not mistaken they offer at least 10.000 req/day in the free plan. https://cloud.google.com/free/

**Comment by kidandcat** [comment]
Is not the free tier in Zeit, but because it is the old api v1, it has limits too. I'm looking to move the server to v2 serverless api

**Comment by RamyaAshika** [comment]
Got a same error @kidandcat

**Comment by RamyaAshika** [comment]
Whether it works now? @pReya

**Comment by kidandcat** [comment]
In 2-3 hours it will be working

**Comment by kidandcat** [comment]
Because I moved the server to Zeit Now. But because it is not prepared to be run on stateless Lambda functions, it is running in old now deployments, and Zeit is pushing its new stateless api and so limiting the old one. I'm moving this back to OVH until I completely rewrite PeerJS server.

This time I'll be using OVH VPS Cloud, which gives a 99,99% SLA by having your machine replicated in 3 different datacenters.

**Comment by kidandcat** [comment]
PeerServer is successfully deployed to OVH servers. PeerJS should work as always.

**Comment by RamyaAshika** [comment]
ooh Okay but one thing I'm noticing that I'm not seeing any error which is related ICE failed when I'm in the different wireless network, Why whether it has happened due to deployment? @kidandcat

**Comment by kidandcat** [comment]
That's very unlikely because ICE servers have nothing related with where the PeerJS Server signaling server is located. Maybe anything in your network changed. That's the true problem of WebRTC, network topologies are very complex and so there are a lot of things that can go wrong.

Today networks are very well prepared to establish connections to the outside, but they are missing reliability in establishing  incoming connections (standard user networks I mean). That's why is so hard to debug this library and WebRTC in general.
