### ISSUE TITLE
readyState of undefined

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#520]
When I have tested with two peers? I got this error and Its no longer working for me? @afrokick @kidandcat 

Uncaught TypeError: Cannot read property 'readyState' of undefined

**Comment by afrokick** [comment]
Could you please provide an error stack?

**Comment by afrokick** [comment]
I found a possible issue. Check it please #521

**Comment by afrokick** [comment]
#521

**Comment by RamyaAshika** [comment]
Hi, @afrokick, Ok But I still can't able to see https://peerjs.com/ the stable version from here and one more this how can I use that because I'm just using your script??

**Comment by RamyaAshika** [comment]
Now the different issue is happening. Its Not working with safari to chrome browser. @afrokick

**Comment by afrokick** [comment]
> Now the different issue is happening. Its Not working with safari to chrome browser. @afrokick

Pease, open a new issue. This issue relates to readyState.

**Comment by balintx99** [comment]
I have this problem as well, sometimes not all the times and I could not figure out what it is related to, but mostly on mobiles (and on one desktop machine :D ) messages and data just do not arrive to the partner. It got this error with "readyState of undefined".

So I copied the merge that you did to solve it and rebuilt it localy, now the error dissapeared but, messages still don't get through. Strangely enough if I call the other one it recognizes the call, but when I answer it no picture or audio is appearing.

I have really no idea what can couse this problem, so out of nowhere :D Otherwise this is a wonderfull package and many thanks for maintaining it 🙏
