### ISSUE TITLE
WebRTC multi party mesh with peerjs

### ISSUE THREAD

**Issue by nikpakar** [peers/peerjs#663]
Is it possible to do multi party webrtc (possibly 4-6) in mesh topology using peerjs and peerjs-server ?

**Comment by ffeytons** [comment]
Hi nikpakar, depends on what exactly you think about when talking about mesh topology.

On my side I've done it with this configuration:
1. A peerjs-server used "normally" I'd say
2. A peerjs webpage that acts as an "host" and which waits for "clients" to connect to it
---> Whenever you start the webpage as a "host", it displays the Peer ID so that the user can share it with the people he/she wants to invite
3. Another peerjs webpage that acts as a "client" and which connects to the host using the host Peer ID.
To be clear the host is not a web server, the host is the browser of one of the participants.

Then the mechanism is as follow:
- Each time a new client connects to the host, the host sends to all connected clients an array with the names and Peer IDs of everyone.
- In my case I've done a belote card game with a videochat -- whenever someone activates its webcam, the code will use the received array to initiate a videostream with all of the participants.

It works pretty good, but as the belote game is limited to 4 players, this means as a user you send your stream to "only" 3 other people. Now each time you add a stream in this "mesh" topology, you consume more bandwidth and more CPU on the user's computer so not sure you can go safely to a lot of people in the room -- if what you want to do is videostream of course.

From my experience, one of the challenges with this is to handle the disconnections - it happens that the WebRTC connection breaks, it happens that the peerjs-to-peerjs-server connection breaks as well and managing a smooth and transparent reconnection requires a bit of work (I did not do it yet).

If you want to have a look at the result, you can go to this URL, this is the video-chat / belote game I've done to play with some of my friends. To test it, just open 4 tabs -- one for the host, 3 for the invitees. I've only tested it on the latest Chrome version:
--> https://belote.fun

**Comment by cngeru** [comment]
How can one expand to 30 users ?

**Comment by stefanache** [comment]
because resource of computer's participant is limited can try use without video(message+audio only)
if not work must o use sfu or mcu server for more particpants
