### ISSUE TITLE
Lost connection, !! urgent

### ISSUE THREAD

**Issue by RamyaAshika** [peers/peerjs#741]
I'm facing error suddenly
POST https://0.peerjs.com/peerjs/test/ov4k6xm3bhh/id?i=0 net::ERR_CONNECTION_TIMED_OUT when connecting two peers. Please I donno why its happening. It was worked early and now suddenly @afrokick @kidandcat

**Comment by kidandcat** [comment]
We have said many times that we offer a public server so you can test the library easily. If you have a service based on peerjs you should set up your own PeerServer.

The public server has suddlently received a lot of network traffic, that's why it is non responsive:

![Captura de pantalla 2020-10-02 182805](https://user-images.githubusercontent.com/3855826/94947087-5d07ae00-04dd-11eb-95c0-0e73e7ae4220.png)

**Comment by RamyaAshika** [comment]
Is that possible to get any instruction/steps to deploy our own peerjs
server. If we did, it will not have any connection issue? Please advise
