### ISSUE TITLE
This peer cannot reconnect to the server. It has already been destroyed.

### ISSUE THREAD

**Issue by JAA17** [peers/peerjs#880]
**Question: So how do I prevent this error, while allowing the user to disconnect at their option (button click) but allow the auto reconnect to occur as well when there is an accidental disconnect - ie momentary loss of internet?**

I get the error:

**This peer cannot reconnect to the server. It has already been destroyed.**

This is my code to disconnect. Its in a class, where m_Connection is the connection to the other user and m_Peer is the PeerJS object.

```
if (this.m_Connection) {
    this.m_Connection.close();
    this.m_Connection = null;
}
if(this.m_Peer){
     this.m_Peer.disconnect();
     this.m_Peer.destroy();
     this.m_Peer = null;
 }

```

I have found why this has happened. Because I have:

```
this.m_Peer.on('disconnected', function () {
    if(this.m_Peer){
        this.m_Peer.id = this.m_IdLast;
        this.m_Peer._lastServerId = this.m_IdLast;
        this.m_Peer.reconnect();
    }
})
```;

**Question: So how do I prevent this error, while allowing the user to disconnect at their option (button click) but allow the auto reconnect to occur as well when there is an accidental disconnect - ie momentary loss of internet?**

**Comment by tareqdayya** [comment]
I'm in the same boat, and even though I'm checking for whether the peer has been `destroyed` before attempting reconnect, I'm still ending up with the error.

**Comment by afrokick** [comment]
Why you destroy the `Peer` object? Just use `disconnect` method on it without calling `destroy`.

**Comment by yashvi53** [comment]
Here In  Peerjs it is not reconnect after Lost connection Like when  i am trying to reconnect with same ID it will not connect
also in if connection closed then also it will not reconnect with same Id 
so here what can i do for that

**Comment by emergent-reasons** [comment]
@afrokick The original post was destroying for some reason, but I think the others here with the problem are not.

It seems if the peer connection gets broken (e.g. a browser tab loses visibility), then it loses its id, and reconnect() then always fails.

Attempting to set id manually before reconnect doesn't work because it's a readonly property. Not sure if server id would also need to be set, or if this manual approach even makes any sense. It seems that the main issue is that the peer node seems to get wiped even when it's not intentionally destroyed.
