### ISSUE TITLE
Connections getting closed after a while

### ISSUE THREAD

**Issue by VladSalat666** [peers/peerjs#898]
When using TURN and relay iceTransportPolicy, after about a minute all opened connections getting closed and each connection emits error "Negotiation failed"
Second peer that has been connected doesn't emit close event
debug shows `PeerJS:  iceConnectionState changed to disconnected on the connection with`

**Comment by afrokick** [comment]
Which turn service did you use? I remember some similar issue this Coturn, but it is not peerjs issue. You should properly configure your TURN service.

Another important thing - currently PeerJS close the connection after iceConnectionState set to disconnected. But for `real case` apps it should be wrong, because ice can be connected again after a while.

You can just reset it behaviour by:

```
    call.peerConnection.oniceconnectionstatechange = () => {
      const state = peerConnection.iceConnectionState;

      console.log(`WebCall: iceConnectionStateChanged:${state}`);
    };
```
