### ISSUE TITLE
Weird behavior between call and answer.

### ISSUE THREAD

**Issue by eko234** [peers/peerjs#933]
Lets say we have two clients, A and B, if A  calls B providing a media stream that only has an audio stream and B answers having both an audio stream and a video stream, client A will not receive B's video stream but only his audio stream.

Its like you only receive the kind of streams you share, any clue on why would this be like that? 

thanks for your time.

**Comment by vimavis** [comment]
Hi!, the problem here is the transceivers, when a call is created from user A that only has audio, the video transceiver is not created, which prevents user B from sending his video. This is fixed by adding the transceiver to the peer connection, when user A creates the call.
Make a fork with that solution, I'll leave it here for you to look at.

https://github.com/peers/peerjs/pull/930/files#diff-71778fd99bfa40eb5bdd47f7f79c7a54e8ff93539972e0dbddaac3d015652ffc

Option B is to add a fake stream (canvas) to simulate the video.

All the best

**Comment by eko234** [comment]
Wow, thank you so much for the quick answer, I will try this out, I don't understand quite wall what a transceiver is, but would like to ask you if my case is caused due to a browser, protocol or library thing.

**Comment by vimavis** [comment]
In a few words, a transceiver is like a track where a stream track is transmitted, a transceiver for the audio track and another for the video track.

**Comment by eko234** [comment]
The fake canvas worked out, thank you so much again, I hope they accept your PR soon, have a nice one. : )

**Comment by eko234** [comment]
For some reason using the fake videostream causes conflict with the audio in a simmilar fashion, I finally decided to fork your pr and it now works like a charm, just letting it here in case someone finds it useful, thanks again @vimavis.
