### ISSUE TITLE
Works on WIFI but not in 4G

### ISSUE THREAD

**Issue by topheman** [peers/peerjs#948]
Hi,

PeerJS is working as expected on WIFI, however, when I try to connect via 4G, on Chrome, I get a `server-error` : `Could not get an ID from the server`, on Safari, it just hangs on.

Steps to reproduce : 

Use any device, go to https://webrtc-remote-control.vercel.app/counter-vanilla/master.html .

Expected behavior: you should see a Qrcode and be able to use the app (ok on WIFI)

Without WIFI

- the Qrcode doesn't show
- Chrome: 
  - in the network panel you will see the request `https://0.peerjs.com/peerjs/id?ts=xxxxxx` failing after a few seconds
  - then the error `Could not get an ID from the server` will show
- Safari
  - in the network panel you will see the request `https://0.peerjs.com/peerjs/id?ts=xxxxxx` that doesn't end

Reproduced on : 

- Chrome 100.0.4896.127 with a Macbook on MacOS 12.3.1, connected to internet via iphone via 4G
- Safari desktop 15.4 with a Macbook on MacOS 12.3.1, connected to internet via iphone via 4G
- Safari mobile 15.4 with iPhone 13 via 4G

Using PeerJS v1.3.2

**Comment by topheman** [comment]
I have asked a few people to do the test, it seems to be a problem with my phone carrier (orange - France).

This is the first time it happens. Has anybody encountered this kind of problem before ? WebRTC behaving weirdly on a specific carrier ? might be causing peerJS server to fail to answer.

**Comment by jonasgloning** [comment]
Hi @topheman, thanks for the detailed report!

The protocol of the server request is not WebRTC, but websocket.
Can you access other websockets? For example [WS Demo](https://libwebsockets.org/testserver/).

Also, please try `1.peerjs.com` as an alternative host.

**Comment by topheman** [comment]
Thx @jonasgloning using 1.peerjs.com works. My config : 

```js
{
  host: "1.peerjs.com",
  port: 443,
  path: "/",
}
```

Sometimes, I need to reload the page to get the connexion right. I will investigate.

**Comment by jonasgloning** [comment]
Glad to hear that!

Some background information:
`1.peerjs.com` and `0.peerjs.com` are connected to the same server (so their respective clients can talk to each other), but connected to the Internet via different reverse proxies.
The former runs through [Cloudflare](https://www.cloudflare.com/de-de/network/). Because so much Internet traffic goes through Cloudflare it may be less likely to have network problems to the client. The other one runs at the hosting provider [Hetzner](https://www.hetzner.com). Network issues should be rare, either way. But it’s good to have options.

This is all a snapshot and a lot will change here. `1.peerjs.com` will probably stay online, but I can’t make any guarantees for a provider.
